Added a notebook with dynamic prompting.
Azure/openai-samples pull request #27
Opened 2023-04-25 04:50 UTC by Sshanu

Adding an example notebook with solves a multi-class classification task using a dataset from Huggingface dataset hub using a completion prompt. The prompt is generated dynamically for any given input using similar examples from a training dataset. This type of dynamic prompting has been shown to outperform static prompts where the same set of examples are used independent of the input.

* Dataset used: Trec dataset
* Task: Question classification into different semantic classes
* Model: Completion model
* Result: Dynamic Prompt provides 13% gain in accuracy over the static prompt using one example in each of the classes.

2023-04-25 04:51 UTC, Sshanu commented
@microsoft-github-policy-service agree company="Microsoft"

2023-04-25 09:33 UTC, paragagrawal11 approved these changes

2023-04-26 07:00 UTC, arb-ms-git requested changes

2023-04-26 11:52 UTC, Sshanu commented on Basic_Samples/Completions/completions_with_dynamic_prompt.ipynb
> +    "dataset = load_dataset(\"trec\")\n",
I have added the description about the dataset

2023-04-26 11:52 UTC, Sshanu commented on Basic_Samples/Completions/completions_with_dynamic_prompt.ipynb
> +    "# prompt is created by adding one example in each of the classes \n",
Added examples of the prompts for both zero and few shots

2023-04-26 13:07 UTC, arb-ms-git approved these changes

2023-04-26 14:29 UTC, merged